### ISSUE TITLE
Leapp suddenly stopped working 

### ISSUE THREAD

**Issue by RobertDittmann** [Noovolari/leapp#125]
I use BigSur system. Leapp was working fine when suddenly SSO sign in window started „blinking”. I restarted leapp and now I see:

**javascript error occurred in the main**

`leapp error 😕 Uncaught Exception:
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at initWorkspace (/Applications/Leapp.app/Contents/Resources/app.asar/electron/dist/electron/main.js:199:57)
at Object.<anonymous> (/Applications/Leapp.app/Contents/Resources/app.asar/electron/dist/electron/main.js:242:1)
at Module._compile (internal/modules/cjs/loader.js:1145:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
at Module.load (internal/modules/cjs/loader.js:981:32) `

I tried to uninstall it and install again few times but it still appears. 

How to solve it ?

**Comment by RobertDittmann** [comment]
some logs:

`[2021-06-10 18:35:53.826] [info] [renderer] execute from Leapp:  {
  error: Error: Command failed: /usr/local/bin/az account clear 2>&1

      at ChildProcess.exithandler (child_process.js:312:12)
      at ChildProcess.emit (events.js:310:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:310:20)
      at Pipe.<anonymous> (net.js:672:12) {
    killed: false,
    code: 127,
    signal: null,
    cmd: '/usr/local/bin/az account clear 2>&1'
  },
  standardout: '/bin/sh: /usr/local/bin/az: No such file or directory\n',
  standarderror: ''
}
[2021-06-10 18:35:54.794] [info] [renderer] execute from Leapp:  {
  error: Error: Command failed: /usr/local/bin/az account clear 2>&1

      at ChildProcess.exithandler (child_process.js:312:12)
      at ChildProcess.emit (events.js:310:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:310:20)
      at Pipe.<anonymous> (net.js:672:12) {
    killed: false,
    code: 127,
    signal: null,
    cmd: '/usr/local/bin/az account clear 2>&1'
  },
  standardout: '/bin/sh: /usr/local/bin/az: No such file or directory\n',
  standarderror: ''
}
[2021-06-10 18:35:54.854] [info] [renderer] execute from Leapp:  {
  error: Error: Command failed: /usr/local/bin/az account clear 2>&1

      at ChildProcess.exithandler (child_process.js:312:12)
      at ChildProcess.emit (events.js:310:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:310:20)
      at Pipe.<anonymous> (net.js:672:12) {
    killed: false,
    code: 127,
    signal: null,
    cmd: '/usr/local/bin/az account clear 2>&1'
  },
  standardout: '/bin/sh: /usr/local/bin/az: No such file or directory\n',
  standarderror: ''
}
[2021-06-10 18:35:58.705] [info] [renderer] execute from Leapp:  {
  error: Error: Command failed: /usr/local/bin/az account clear 2>&1

      at ChildProcess.exithandler (child_process.js:312:12)
      at ChildProcess.emit (events.js:310:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:310:20)
      at Pipe.<anonymous> (net.js:672:12) {
    killed: false,
    code: 127,
    signal: null,
    cmd: '/usr/local/bin/az account clear 2>&1'
  },
  standardout: '/bin/sh: /usr/local/bin/az: No such file or directory\n',
  standarderror: ''
}
[2021-06-10 18:36:00.662] [info] [renderer] execute from Leapp:  {
  error: Error: Command failed: /usr/local/bin/az account clear 2>&1

      at ChildProcess.exithandler (child_process.js:312:12)
      at ChildProcess.emit (events.js:310:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Socket.<anonymous> (internal/child_process.js:443:11)
      at Socket.emit (events.js:310:20)
      at Pipe.<anonymous> (net.js:672:12) {
    killed: false,
    code: 127,
    signal: null,
    cmd: '/usr/local/bin/az account clear 2>&1'
  },
  standardout: '/bin/sh: /usr/local/bin/az: No such file or directory\n',
  standarderror: ''
}`

**Comment by andreacavagna01** [comment]
looks like your workspace is compromised, you can restore leapp by removing the file inside the Leapp config file `Leapp-lock.json` inside the `.Leapp` directory.
By doing this your Sessions will be lost and you have to manually re-add them, but Leapp will start working.

With the new release, all those workspace compatibilities will be tested automatically and this problem should disappear.

I'm sorry for this drastic resolution of your problem

**Comment by RobertDittmann** [comment]
@andreacavagna01 THX it worked for me :)
