### ISSUE TITLE
Error on APP startup

### ISSUE THREAD

**Issue by ale7canna** [Noovolari/leapp#128]
**Describe the bug**
I am on MacOS 11.4. I was able to start and configure the app some days ago. Today I got the following error: _A JavaScript error occurred in the main process_
Uncaught Exception:
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at initWorkspace (/Applications/Leapp.app/Contents/Resources/app.asar/electron/dist/electron/main.js:216:57)
at Object.<anonymous> (/Applications/Leapp.app/Contents/Resources/app.asar/electron/dist/electron/main.js:230:1)
at Module._compile (internal/modules/cjs/loader.js:1145:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
at Module.load (internal/modules/cjs/loader.js:981:32)
at Module._load (internal/modules/cjs/loader.js:881:14)
at Function.Module._load (electron/js2c/asar.js:769:28)
at Object.<anonymous> (electron/js2c/browser_init.js:185:3494)
at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3698)

In the home directory, I found `.Leapp` directory with 2 files. `.latest.json` reported 0.5.3. `Leapp-lock.json` was stangely empty.
I deleted the whole `.Leapp` directory in order to unblock me. Obviously I had to configure the whole env again.

**Leapp Version**
0.5.3

**Screenshots**
![image](https://user-images.githubusercontent.com/6455544/123935167-4327c880-d994-11eb-85db-39b3d2a5ea22.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - OS Version: 11.4
 - Leapp Version: 0.5.3

**Comment by ericvilla** [comment]
Hi @ale7canna, as we can't reproduce the bug you've encountered, we've to consider this issue as closed.
I suggest you try the new [v0.6.0](https://github.com/Noovolari/leapp/releases/tag/v0.6.0) version to understand if the problem persists. Please, back up your current Leapp-lock.json file before updating to v0.6.0
