### ISSUE TITLE
v0.7.4 is not working on macbook pro with M1 pro chip

### ISSUE THREAD

**Issue by orenaksakal** [Noovolari/leapp#190]
**Describe the bug**
Bug: v0.7.4 is displaying blank on MacBook pro with M1 pro chip, when the app is launched view is empty.
Workaround: v0.7.3 is working fine

**Leapp Version**
v0.7.4

**To Reproduce**
1. Open app on your m1 pro macbook
4. See empty view

**Expected behavior**
App to load initial screen

**Screenshots**
![Screenshot 2021-11-16 at 11 27 49](https://user-images.githubusercontent.com/199699/141969188-7ff93f6b-2b00-49e6-b699-0426fef29879.jpg)

**Desktop (please complete the following information):**
 - OS: MacOs
 - OS Version: Monterey
 - Leapp Version: v0.7.4

**Additional context**
v0.7.3 is working fine

**Comment by ericvilla** [comment]
Thank you for the bug report @orenaksakal! Can you please provide your logs under ~/Library/Logs/Leapp/log.log?

**Comment by alucio-echen** [comment]
I am also running into this issue. I do not see a log.log file being generated. But the log.electronService.log file contains:

`[2021-11-18 22:16:12.916] [error] [renderer] [ir] No sessions to stop, skipping... TypeError: this.electronService.log is not a function
    at D.cleanCredentialFile (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.eaf3dd68171dbd6ae6a3.js:1:1335311)
    at ir.beforeCloseInstructions (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.eaf3dd68171dbd6ae6a3.js:1:1436846)
    at EventEmitter.<anonymous> (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.eaf3dd68171dbd6ae6a3.js:1:1435771)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:1017)
`

**Comment by viertaxa** [comment]
I am also getting this error on a M1 Max MBP:

```
[2021-11-19 12:43:04.822] [error] [renderer] [ir] No sessions to stop, skipping... TypeError: this.electronService.log is not a function
    at D.cleanCredentialFile (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.eaf3dd68171dbd6ae6a3.js:1:1335311)
    at ir.beforeCloseInstructions (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.eaf3dd68171dbd6ae6a3.js:1:1436846)
    at EventEmitter.<anonymous> (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.eaf3dd68171dbd6ae6a3.js:1:1435771)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:1017)
```

**Comment by PatrykMilewski** [comment]
Works fine on non-pro M1 chip.

**Comment by itemka** [comment]
I've got the same trouble (M1), I closed it forced quite, and opened again and it works fine.

**Comment by andreacavagna01** [comment]
The issue should be fixed in the [latest release](https://www.leapp.cloud/releases), check it out and let me know.

Thanks for reporting @itemka

**Comment by itemka** [comment]
@andreacavagna01 Yep, I checked it on the last version (v0.8.0) and it has opened for the second time and now works fine.

**Comment by pethron** [comment]
Closing. Feel free to reopen if this problem arises again.

**Comment by adventurini** [comment]
Rose again...
