### ISSUE TITLE
Can't start a new session anymore 

### ISSUE THREAD

**Issue by nimesh-notifi** [Noovolari/leapp#275]
**Leapp Version**
Windows 11, Leapp 0.12

**To Reproduce**
1. Start Leapp
2. Attempt to start a session.

**Expected behavior**
New credentials are populated in aws credentials file

Logs:
[2022-05-16 07:35:22.262] [info]  [renderer] execute from Leapp:  {
  error: null,
  standardout: 'aws-cli/2.6.0 Python/3.9.11 Windows/10 exe/AMD64 prompt/off\r\n',
  standarderror: ''
}
[2022-05-16 07:35:22.327] [info]  [renderer] execute from Leapp:  { error: null, standardout: '1.2.312.0\n', standarderror: '' }
[2022-05-16 07:35:28.456] [info]  [renderer] [Hd] Starting Session {
   "timestamp": "2022-05-16T14:35:28.456Z",
   "id": "ea722b7e-2025-41bb-9f8f-46e3614f00c4",
   "account": "prd",
   "type": "awsSsoRole"
}
[2022-05-16 07:35:28.716] [error] [renderer] Session token not found or invalid UnauthorizedException: Session token not found or invalid
    at Object.m [as extractError] (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2143146)
    at constructor.b (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2148042)
    at constructor.callListeners (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2173037)
    at constructor.emit (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2172747)
    at constructor.emitEvent (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2158642)
    at constructor.b (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2154150)
    at A.runTo (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2227328)
    at file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2227533
    at constructor.<anonymous> (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2154440)
    at constructor.<anonymous> (file:///C:/Users/nimek/AppData/Local/Programs/Leapp/resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2158697)

**Comment by nimesh-notifi** [comment]
It seems like leapp is failing to open a browser window to complete sso.

'aws configure sso' cli method still works

**Comment by andreacavagna01** [comment]
Added as Bug and assigned to @ericvilla. 
In the meanwhile, I think you can try changing the Auth method of the AWS SSO integration. 
Right-click in the integration menu -> "Edit" -> "Auth. method"
