### ISSUE TITLE
App does not start - Cannot read properties of undefined (reading 'region')

### ISSUE THREAD

**Issue by stav-hacohen** [Noovolari/leapp#278]
**Describe the bug**
App does not start. Only see white window with red error message: Cannot read properties of undefined (reading 'region'). 
See screen shot and logs.

**Leapp Version**
Version 0.12.0 (0.12.0)

**To Reproduce**
Download the app (ARM64)
Move to Applications
Open the app

**Expected behavior**
Start the app normally.

**Things I've tried:**
Install versions 12.0, 11.1, 8.1 ARM64
Install version 12.0 x64
Remove different apps from my Mac
Restart laptop
Connect/Disconnect VPN

Software:

    System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 32 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 7459.121.3
      OS Loader Version: 7459.121.3
      Activation Lock Status: Disabled

![Screen Shot 2022-05-19 at 16 55 05](https://user-images.githubusercontent.com/93873147/169350335-cd026906-2550-4a1b-b669-fc07d8ea0357.png)

From the logs -

[2022-05-21 00:06:16.183] [error] [renderer] Cannot read properties of undefined (reading 'region') TypeError: Cannot read properties of undefined (reading 'region')
at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:1994469
at Generator.next ()
at A (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2627036)
at f (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2627248)
at k.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:6564)
at Object.onInvoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:138984)
at k.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:6504)
at _.run (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:1966)
at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:16827
at k.invokeTask (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:7182)
[2022-05-21 00:06:16.671] [info] [renderer] execute from Leapp: {
error: null,
standardout: 'aws-cli/2.7.2 Python/3.9.11 Darwin/21.5.0 exe/x86_64 prompt/off\n',
standarderror: ''
}
[2022-05-21 00:06:16.687] [info] [renderer] execute from Leapp: { error: null, standardout: '1.2.323.0\n', standarderror: '' }
[2022-05-21 00:06:30.262] [info] [renderer] [Ub] Preparing for closing instruction...
[2022-05-21 00:06:30.263] [info] [renderer] [Ub] Closing app with cleaning process...

**Comment by stav-hacohen** [comment]
From the logs - 

[2022-05-21 00:06:16.183] [error] [renderer] Cannot read properties of undefined (reading 'region') TypeError: Cannot read properties of undefined (reading 'region')
    at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:1994469
    at Generator.next (<anonymous>)
    at A (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2627036)
    at f (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:2627248)
    at k.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:6564)
    at Object.onInvoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.4d04c581dbecd1f6.js:1:138984)
    at k.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:6504)
    at _.run (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:1966)
    at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:16827
    at k.invokeTask (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.6559e0eb1ae52d53.js:1:7182)
[2022-05-21 00:06:16.671] [info]  [renderer] execute from Leapp:  {
  error: null,
  standardout: 'aws-cli/2.7.2 Python/3.9.11 Darwin/21.5.0 exe/x86_64 prompt/off\n',
  standarderror: ''
}
[2022-05-21 00:06:16.687] [info]  [renderer] execute from Leapp:  { error: null, standardout: '1.2.323.0\n', standarderror: '' }
[2022-05-21 00:06:30.262] [info]  [renderer] [Ub] Preparing for closing instruction...
[2022-05-21 00:06:30.263] [info]  [renderer] [Ub] Closing app with cleaning process...

**Comment by stav-hacohen** [comment]
Was able to solve it eventually after deleting ~/.Leapp/Leapp-lock.json

I assume this encrypted file was created during an older installation of Leapp and did not match the new installation. 
I would suggest to choose an option of clean install which will delete this conf file automatically to resolve these kind of issues.

**Comment by andreacavagna01** [comment]
I think it's a good feature for debugging and auto solving problems. 

Thanks for the idea
