### ISSUE TITLE
Leapp crashes on startup (SyntaxError: Unexpected end of JSON input)

### ISSUE THREAD

**Issue by aleksanderaleksic** [Noovolari/leapp#282]
**Describe the bug**
The app crashes when starting up.
Have tried reinstall, restart the computer and deleted both `~/.Leapp` and `/opt/Leapp`

**Leapp Version**
Happens on both 0.12.2 and 0.12.1

**To Reproduce**
Run the app from the terminal or from the desktoop

**Expected behavior**
Expected the app to start

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version 21.10
 - Leapp Version 0.12.2

**Additional context**
```
> leapp
[13331:0601/093309.534427:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
Checking for update
```

Logs:
```
[2022-06-01 09:22:07.161] [error] [renderer] [vg] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at b.deserialize (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:2290314)
    at ee (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:2292215)
    at h.reloadWorkspace (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:1985730)
    at h.getWorkspace (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:1985790)
    at h.getSessions (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:1986300)
    at new p (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:1971959)
    at or.get behaviouralSubjectService [as behaviouralSubjectService] (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:679611)
    at new mp (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:1825866)
    at Object.mp.ɵfac [as factory] (file:///opt/Leapp/resources/app.asar/dist/leapp-client/main.0b104184584da49c.js:1:1828137)
```

**Comment by andreacavagna01** [comment]
I think it's related to an electron issue: https://github.com/electron/electron/issues/32317

Thanks for pointing it out!

**Comment by devnoh** [comment]
I have the same issue, and tried a different versions 0.12.0, 0.12.1 for x64 and arm64 but got the same error screen.
- masOS Monteray 12.4
- Macbook Pro Apple M1 Max
- Leapp Version 0.12.2

<img width="1312" alt="Screen Shot 2022-06-02 at 9 23 26 AM" src="https://user-images.githubusercontent.com/87061/171678054-a78ee4e9-b052-4438-800d-7b54a3d12d60.png">

**Comment by GustafValentine** [comment]
Same on Windows 10 with version 0.12.2. Any workaround known?

**Comment by RomanFerenets** [comment]
Can confirm the problem, have exactly the same type of behavior on my Ubuntu 22.04 LTS machine. Tried both `0.12.2` and `0.12.1` versions.

**Comment by GustafValentine** [comment]
> Hi guys, try to rename your Leapp-lock.json file located in .leapp in your home directory in something with bkp in the name and try restart the app, see if the app is working.

Thanks @urz9999! That unblocked the problem for me, I only needed to re-create my session.

**Comment by josh-onchain** [comment]
+1

**Comment by andreacavagna01** [comment]
Now there is an automatic doctor in Leapp, a previous configuration is saved in a backup file, and Leapp recovers the last configuration once a leapp-lock.json file is corrupted.

I'm closing this issue
