### ISSUE TITLE
Error on the Leapp Desktop APP: reading 'split'

### ISSUE THREAD

**Issue by matheusmgon** [Noovolari/leapp#355]
Hello everyone!

I did start using Leapp app recently.

When I try to use the "Multi-Console Extension"
![image](https://user-images.githubusercontent.com/33628133/200034105-70404486-60e3-4cbb-952f-520a65852544.png)
 
I receive the message error:

![image](https://user-images.githubusercontent.com/33628133/200033885-db102520-01b9-4708-80d1-74e1e3920027.png)

On the file logs, I have this message:

```
[2022-11-04 17:03:33.610] [error] [renderer] [ErrorService] TypeError: Cannot read properties of undefined (reading 'split')
    at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.414818b86baf6dd2.js:10718:42
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.414818b86baf6dd2.js:185945:24)
    at _next (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.414818b86baf6dd2.js:185967:9)
    at _ZoneDelegate.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:424:158)
    at Object.onInvoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.414818b86baf6dd2.js:144980:25)
    at _ZoneDelegate.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:424:46)
    at Zone.run (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:208:37)
    at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:1300:28
    at _ZoneDelegate.invokeTask (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.23a56c6b24ce7905.js:451:171)
```

Anyone can help me?
Thanks.

S.O: MacOS Ventura
ARCH: ARM64(M1)

**Comment by urz9999** [comment]
Hmmm, I suspect that one of the parameters you've used to describe your session is missing or malformed, but still, this means that there is a scenario we didn't test appropriately! Thanks for the issue! We'll check it and reach you as soon as possible, in the meantime, try to give us more context: for example, which session you've tried? Can you give us some of the parameters you've used (if not personal of course)? This could help us speed up investigating the issue! 👍

**Comment by urz9999** [comment]
We have investigated the issue and we suspect that you tried to access the web console with an IAM User session, which, unfortunately, is not possible at the moment. For a typo, the condition to hide the button for that particular session was missing, and we are already planning a new release in the next few days to address this and some other QOL fixes for the extension.
Again, thanks for the issue

**Comment by urz9999** [comment]
Hello, if you can consider this issue done, I would like to close it. In case you'll find other issues, please fill free to reopen it!
