### ISSUE TITLE
Cannot run cdk bootstrap when using Leapp to manage AWS credentials

### ISSUE THREAD

**Issue by 094459** [Noovolari/leapp#435]
**Describe the bug**

I have a CDK stack that I want to deploy into a new AWS account. I have set up this account in Leapp, and I can confirm that I have the right level of access. When I try and bootstrap CDK into this account I get the following error:

```
cdk bootstrap aws://xxxxxxx/eu-west-1

The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 81edc5fe-46db-47d3-83c4-de06d32eeaf3; Proxy: null)
```

**Leapp Version**

Version 0.18.1 (Core: 0.1.139)

**To Reproduce**

Got an an AWS region where CDK has not been bootstrapped
Run the following command:
```
cdk bootstrap aws://{aws-account}/{aws-region}
```

**Expected behavior**
It should complete the CDK bootstrap process.

**Screenshots**
This is the output from my terminal:

```
 ⏳  Bootstrapping environment aws://xxxxxx/eu-west-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
4:57:57 PM | CREATE_FAILED        | AWS::IAM::Role          | CloudFormationExecutionRole
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 865c68a5-62eb-4
83d-815a-17c35f946fbc; Proxy: null)

4:57:57 PM | CREATE_FAILED        | AWS::IAM::Role          | LookupRole
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 7b083eaa-0214-4
9e8-a288-ce8c37a10ac9; Proxy: null)

4:57:57 PM | CREATE_FAILED        | AWS::IAM::Role          | ImagePublishingRole
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 81edc5fe-46db-4
7d3-83c4-de06d32eeaf3; Proxy: null)

4:57:57 PM | CREATE_FAILED        | AWS::IAM::Role          | FilePublishingRole
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 4ff6cd58-6c57-4
bc7-b55f-523801d7cf4e; Proxy: null)

 ❌  Environment aws://665240076514/eu-west-1 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 865c68a5-62eb-483d-815a-17c35f946fbc; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 7b083eaa-0214-49e8-a288-ce8c37a10ac9; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 81edc5fe-46db-47d3-83c4-de06d32eeaf3; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 4ff6cd58-6c57-4bc7-b55f-523801d7cf4e; Proxy: null)
    at FullCloudFormationDeployment.monitorDeployment (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:412:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:417:2104
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:417:1949)
    at async exec4 (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:470:52002)

The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 865c68a5-62eb-483d-815a-17c35f946fbc; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 7b083eaa-0214-49e8-a288-ce8c37a10ac9; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 81edc5fe-46db-47d3-83c4-de06d32eeaf3; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 4ff6cd58-6c57-4bc7-b55f-523801d7cf4e; Proxy: null)
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version Ventura 3.4.1 (22F82)
 - Leapp Version Version 0.18.1 (Core: 0.1.139)

**Additional context**
To resolve the issue, I created (manually) a new IAM user and AWS credentials. I stopped all my Leapp sessions. I then created a new .aws/credentials file and added this new AWS credentials. I was then able to successfully bootstrap CDK.

**Comment by pethron** [comment]
Hi @094459 ! I thinks this is a known bug to how CDK uses the SDK. Try exporting this flag before running it:
`AWS_SDK_LOAD_CONFIG=1`

For reference: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-configured-credential-process.html

**Comment by 094459** [comment]
I just tried this. I deleted the existing cdk bootstrap stack, and then restarted my Leapp session. When I re-ran the bootstrap command I got exactly the same error:

```
export AWS_SDK_LOAD_CONFIG=1
cdk bootstrap aws://xxxx/eu-west-1

 ⏳  Bootstrapping environment aws://xxxxx/eu-west-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
CDKToolkit: creating CloudFormation changeset...
10:32:20 | CREATE_FAILED        | AWS::IAM::Role          | FilePublishingRole
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId;
Request ID: 1f5c5880-9cbe-4b9a-b07d-8475333cdfda; Proxy: null)

10:32:20 | CREATE_FAILED        | AWS::IAM::Role          | ImagePublishingRole
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId;
Request ID: 6d24b36e-8971-4306-95c7-a6c00dad8347; Proxy: null)

10:32:20 | CREATE_FAILED        | AWS::IAM::Role          | CloudFormationExecutionRole
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId;
Request ID: 646caacd-ad8c-4071-b3cb-3b84f2b59314; Proxy: null)

10:32:20 | CREATE_FAILED        | AWS::S3::Bucket         | StagingBucket
cdk-hnb659fds-assets-665240076514-eu-west-1 already exists

10:32:20 | CREATE_FAILED        | AWS::IAM::Role          | LookupRole
The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId;
Request ID: 18506d80-b44e-4aa5-a9a2-77c382980c06; Proxy: null)

 ❌  Environment aws://xxxxxx/eu-west-1 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 1f5c5880-9cbe-4b9a-b07d-8475333cdfda; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 6d24b36e-8971-4306-95c7-a6c00dad8347; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 646caacd-ad8c-4071-b3cb-3b84f2b59314; Proxy: null), cdk-hnb659fds-assets-665240076514-eu-west-1 already exists, The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 18506d80-b44e-4aa5-a9a2-77c382980c06; Proxy: null)
    at FullCloudFormationDeployment.monitorDeployment (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:412:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:417:2104
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:417:1949)
    at async exec4 (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:470:52002)

The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 1f5c5880-9cbe-4b9a-b07d-8475333cdfda; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 6d24b36e-8971-4306-95c7-a6c00dad8347; Proxy: null), The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 646caacd-ad8c-4071-b3cb-3b84f2b59314; Proxy: null), cdk-hnb659fds-assets-665240076514-eu-west-1 already exists, The security token included in the request is invalid (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 18506d80-b44e-4aa5-a9a2-77c382980c06; Proxy: null)
```

**Comment by pethron** [comment]
Can you try to remove the aws_session_token manually from the AWS configuration file and re-run the bootstrap?

**Comment by 094459** [comment]
When I do that and re run, I get the following error:

```
 ⏳  Bootstrapping environment aws://xxxxx/eu-west-1...
 ❌  Environment aws://xxxx/eu-west-1 failed bootstrapping: InvalidClientTokenId: The security token included in the request is invalid.
    at Request.extractError (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:46430)
    at Request.callListeners (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:89761)
    at Request.emit (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:89209)
    at Request.emit (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:195751)
    at Request.transition (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:189303)
    at AcceptorStateMachine.runTo (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:154175)
    at /Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:154505
    at Request.<anonymous> (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:189595)
    at Request.<anonymous> (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:195826)
    at Request.callListeners (/Users/ricsue/.nvm/versions/node/v18.15.0/lib/node_modules/aws-cdk/lib/index.js:307:89929) {
  code: 'InvalidClientTokenId',
  time: 2023-06-28T09:41:19.254Z,
  requestId: '94b42420-23e7-4408-a6ee-60751d35f9b8',
  statusCode: 403,
  retryable: false,
  retryDelay: 63.376988869357206
}

The security token included in the request is invalid.
```

**Comment by pethron** [comment]
Have you tried to regenerate the credentials through Leapp after exporting?

**Comment by pethron** [comment]
BTW, be sure to remove even the cache:
`rm -r ~/.aws/cli/cache`

**Comment by pethron** [comment]
I was referring to this exact process. I don't know what's going wrong since I usually fixed CDK problems this way; I summon @ericvilla maybe he can be of help.

**Comment by bertini-besharp** [comment]
Hi, same issue here!

**Comment by pethron** [comment]
I just thought of a possible problem. If your CDK template is provisioning something on IAM you need to set up MFA.
So the problem could boil down to just that. Have you some IAM call in your template @094459 and @bertini-besharp ?

`The temporary security credentials created by GetSessionToken can be used to make API calls to any Amazon Web Services service with the following exceptions:

You cannot call any IAM API operations unless MFA authentication information is included in the request.
You cannot call any STS API except AssumeRole or GetCallerIdentity .`

https://docs.aws.amazon.com/cli/latest/reference/sts/get-session-token.html

**Comment by 094459** [comment]
I will certainly give this a go - at this stage, this is just bootstrapping CDK, but looking at the template that gets produced, it defo has IAM calls in there.

**Comment by pethron** [comment]
The workaround would be to setup an MFA for the IAM user or switch to roles

**Comment by 094459** [comment]
When you say "switch to roles" - just so I am clear, what do you mean? When I am in Leapp, I get three options: AWS IAM Role Federated, AWS IAM User, and AWS IAM role chained. Or are you referring to something else?

**Comment by 094459** [comment]
So I just enabled MFA for the user I was using within Leapp, installed FreeOTP and then integrated this with my AWS account and tested to make sure it was all working. My user was now using MFA to login in - all good.

I tried again using Leapp, and got the same error.

Thinking this might be a cached record or maybe its saved something from before, I deleted and created a new integration in Leapp. I set up my aws Iam user, mfa arn, and AWS access credentials. When I go to login, I never get asked for the token, it just logs me in. When I try and run the cdk bootstrap command, I still get the same error.

**Comment by 094459** [comment]
I just restart my macbook and I am now being requested for my MFA token when I start a session. I retried running the cdk bootstrap command, and it is indeed now working.

Thanks for resolving the issue - I will make sure I use MFA across all my accounts.

**Comment by 094459** [comment]
Issue resolved: Need to ensure you are using MFA with the AWS account when using cdk bootstrap. Once MFA is configured, it works as expected.
