### ISSUE TITLE
HTTP 429 TooManyRequestsException when using 'leapp integration login' cli command

### ISSUE THREAD

**Issue by imanAzi** [Noovolari/leapp#459]
**Describe the bug**
We are using leapp for more than a year now and never had issues. Since yesterday when doing 'leapp integration login' command in our terminal and choosing our SSO integration and authorising in browser, we'll get a HTTP 429 TooManyRequestsException.
The reason why we use leapp integration login, is because the login procedure (both in-browser and in-app) has never worked in the desktop application for us.
 
```
waiting for browser authorization...
/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/protocol/json.js:52
  resp.error = util.error(new Error(), error);
                          ^

TooManyRequestsException: HTTP 429 Unknown Code
    at Object.extractError (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/homebrew/Cellar/leapp-cli/0.1.40/libexec/lib/node_modules/@noovolari/leapp-cli/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'TooManyRequestsException',
  time: 2023-08-10T07:58:23.409Z,
  requestId: 'a5df292e-517c-4b8b-9501-ac1dac5dfb54',
  statusCode: 429,
  retryable: true
}

Node.js v20.3.1
```

**Leapp Version**
Leapp Cli
Version 0.1.40 (Core: 0.1.140)

Leapp GUI:
Version 0.18.4 (0.18.4)

**To Reproduce**
1. leapp integration login in terminal
2. Select SSO integration
3. Allow access in browser
4. Getting HTTP 429 TooManyRequestsException response back in terminal

**Expected behavior**
After allowing in browser, we are authenticated and can choose on of our profiles in leapp desktop.  

**Screenshots**

**Desktop (please complete the following information):**
 - macOS (m1)
 - Ventura 13.3.1. 
 - Leapp Cli version 0.1.40 (Core: 0.1.140)
 - Leapp desktop cersion Version 0.18.4 (0.18.4)

**Additional context**

**Comment by pethron** [comment]
Hello @imanAzi , thanks for reporting. We've already worked out a fix and will release it today or tomorrow; our guess is that AWS changed the implementation of their throttling mechanism, so we had to modify ours as well.

**Comment by pethron** [comment]
Btw, if you want to give it a go with the app again now it should work!

**Comment by pethron** [comment]
Fixed with https://github.com/Noovolari/leapp/releases/tag/v0.18.5 and https://www.npmjs.com/package/@noovolari/leapp-cli/v/0.1.42
