### ISSUE TITLE
Azure: `Error: Cannot read properties of undefined (reading 'expires_on')` 

### ISSUE THREAD

**Issue by pat-s** [Noovolari/leapp#460]
**Describe the bug**
Starting an Azure session errors with `Error: Cannot read properties of undefined (reading 'expires_on')`. 

**Leapp Version**
Add the version of your Leapp (you can find it under taskbar -> about or Leapp -> about on MacOS X)

**To Reproduce**

1. Login to an Azure account via the Azure integration
2. Start a session

CLI

```
[2023-08-12 10:38:09.744] [info]  [renderer] execute from Leapp
info:{
    "command": "/usr/local/bin/az account get-access-token --subscription <subscription>",
    "stdout": "****",
    "stderr": "****",
    "error": null
}
[2023-08-12 10:38:09.758] [warn]  [renderer] Cannot read properties of undefined (reading 'expires_on')
```

App

```
[2023-08-12 10:34:52.841] [error] [renderer] [AzureIntegrationService] Error: Error: Command failed: /usr/local/bin/az login --tenant <tenant> 2>&1

    at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.ba8a1149c0f5cc08.js:21646:15
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.ba8a1149c0f5cc08.js:108555:24)
    at _throw (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.ba8a1149c0f5cc08.js:108581:9)
    at _ZoneDelegate.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.800b33145f9b37f4.js:504:158)
    at Object.onInvoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/main.ba8a1149c0f5cc08.js:169994:25)
    at _ZoneDelegate.invoke (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.800b33145f9b37f4.js:504:46)
    at Zone.run (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.800b33145f9b37f4.js:243:37)
    at file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.800b33145f9b37f4.js:1589:28
    at _ZoneDelegate.invokeTask (file:///Applications/Leapp.app/Contents/Resources/app.asar/dist/leapp-client/polyfills.800b33145f9b37f4.js:537:171)
[2023-08-12 10:36:23.437] [info]  [renderer] Removing sessions with attached integration id: 5197e9ff-84f2-495f-bb65-e68c3abf327b
[2023-08-12 10:36:36.640] [info]  [renderer] Starting Session
[2023-08-12 10:36:37.019] [info]  [renderer] execute from Leapp
```

**Expected behavior**
Session starts.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version [e.g. 22]
 - Leapp Version 0.18.5

**Additional context**
I can start sessions for which I am having full access to the tenant. The session which fails to start is from another subscription with limited permissions.

**Comment by pethron** [comment]
Hi @pat-s, thanks for reporting. Can you disclose the permissions associated with the subscription?

**Comment by pat-s** [comment]
> Can you disclose the permissions associated with the subscription?

No. As reported, the sub is from a tenant for which I only have limited permissions.
