### ISSUE TITLE
Cannot build desktop app from source

### ISSUE THREAD

**Issue by ribugent** [Noovolari/leapp#512]
**Describe the bug**
Hello

I'm trying to build the desktop app on Linux arm64, since there isn't releases for this cpu, but everytime I try it, it fails. I checked the github workflow and it seems to build this properly some external repository code is needed. 

**Leapp Version**
0.23

**To Reproduce**
1. Clone repository
2. `cd leapp/packages/desktop-app`
3. `npm install`
4. `npm run build-prod`
5. Build error

```
> Leapp@0.23.0 build-prod
> gushio gushio/target-build.js 'configuration production'

Performing cleanup... 
Cleanup completed successfully
Building leapp... 
- Searching dependency tree
make: Entering directory '/home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/@noovolari/dpapi-addon/build'
  CXX(target) Release/obj.target/dpapi/dpapi-addon/main.o
In file included from /home/ribu/.electron-gyp/22.3.25/include/node/v8-object.h:10,
                 from /home/ribu/.electron-gyp/22.3.25/include/node/v8-array-buffer.h:13,
                 from /home/ribu/.electron-gyp/22.3.25/include/node/v8.h:24,
                 from /home/ribu/.electron-gyp/22.3.25/include/node/node.h:79,
                 from ../../../nan/nan.h:62,
                 from ../dpapi-addon/main.cpp:6:
/home/ribu/.electron-gyp/22.3.25/include/node/v8-persistent-handle.h:256:44: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  256 |   using CopyablePersistent = Persistent<T, CopyablePersistentTraits<T>>;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ribu/.electron-gyp/22.3.25/include/node/v8-persistent-handle.h:255:48: note: declared here
  255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
../../../nan/nan.h:208:16: warning: ‘template<class T> struct v8::CopyablePersistentTraits’ is deprecated: Use v8::Global instead [-Wdeprecated-declarations]
  208 |     public v8::CopyablePersistentTraits<T> {};
      |                ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ribu/.electron-gyp/22.3.25/include/node/v8-persistent-handle.h:255:48: note: declared here
  255 | struct V8_DEPRECATED("Use v8::Global instead") CopyablePersistentTraits {
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ribu/.electron-gyp/22.3.25/include/node/node.h:896:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>)’ to ‘node::addon_context_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, void*)’} [-Wcast-function-type]
  896 |       (node::addon_context_register_func) (regfunc),                  \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ribu/.electron-gyp/22.3.25/include/node/node.h:914:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE_X’
  914 |   NODE_MODULE_CONTEXT_AWARE_X(modname, regfunc, NULL, 0)
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ribu/.electron-gyp/22.3.25/include/node/node.h:945:3: note: in expansion of macro ‘NODE_MODULE_CONTEXT_AWARE’
  945 |   NODE_MODULE_CONTEXT_AWARE(NODE_GYP_MODULE_NAME,                     \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
../dpapi-addon/main.cpp:32:1: note: in expansion of macro ‘NODE_MODULE_INIT’
   32 | NODE_MODULE_INIT()
      | ^~~~~~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/dpapi.node
  COPY Release/dpapi.node
make: Leaving directory '/home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/@noovolari/dpapi-addon/build'
✔ Rebuild Complete
- Generating browser application bundles (phase: setup)...
✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.

./src/app/app.component.ts:7:0-51 - Error: Module not found: Error: Can't resolve './leapp-team-core/user/role' in '/home/ribu/Develop/ribugent/leapp/packages/desktop-app/src/app'

Error: src/app/app.component.ts:34:22 - error TS2307: Cannot find module './leapp-team-core/user/role' or its corresponding type declarations.

34 import { Role } from "./leapp-team-core/user/role";
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/app/services/analytics.service.ts:3:22 - error TS2307: Cannot find module '../leapp-team-core/user/user' or its corresponding type declarations.

3 import { User } from "../leapp-team-core/user/user";
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



[Gushio|Script] Error while running '/home/ribu/Develop/ribugent/leapp/packages/desktop-app/gushio/target-build.js': Error: - Generating browser application bundles (phase: setup)...
✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.

./src/app/app.component.ts:7:0-51 - Error: Module not found: Error: Can't resolve './leapp-team-core/user/role' in '/home/ribu/Develop/ribugent/leapp/packages/desktop-app/src/app'

Error: src/app/app.component.ts:34:22 - error TS2307: Cannot find module './leapp-team-core/user/role' or its corresponding type declarations.

34 import { Role } from "./leapp-team-core/user/role";
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/app/services/analytics.service.ts:3:22 - error TS2307: Cannot find module '../leapp-team-core/user/user' or its corresponding type declarations.

3 import { User } from "../leapp-team-core/user/user";
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




    at compileFunction (/home/ribu/Develop/ribugent/leapp/packages/desktop-app/gushio/compile-func.js:7:11)
    at Object.run [as runFunction] (/home/ribu/Develop/ribugent/leapp/packages/desktop-app/gushio/target-build.js:35:13)
    at async file:///home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/gushio/runner/Runner.js:135:17
    at async FunctionWrapper.run (file:///home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/gushio/runner/patches/FunctionWrapper.js:23:24)
    at async Runner.onCommandAction (file:///home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/gushio/runner/Runner.js:128:9)
    at async file:///home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/gushio/runner/Runner.js:147:33
    at async Command.<anonymous> (file:///home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/gushio/runner/ScriptHandler.js:38:13)
    at async Command.parseAsync (/home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/gushio/node_modules/commander/lib/command.js:916:5)
    at async Runner.run (file:///home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/gushio/runner/Runner.js:149:9)
    at async Command.<anonymous> (file:///home/ribu/Develop/ribugent/leapp/packages/desktop-app/node_modules/gushio/cli/cliProgram.js:39:17)
```

**Expected behavior**
Build sucessfully

**Desktop (please complete the following information):**
 - OS: Arch Linux ARM (aarch64)
 - Leapp Version 0.23

**Additional context**

**Comment by andreacavagna01** [comment]
Thanks for noticing! It's a bug in the stub of the Team service. We need to fix that internal library to make it work again.

@ericvilla, can we help you here?

**Comment by ericvilla** [comment]
Hi @ribugent! Sorry for the late response. The app.component.ts is now fixed (from an importing p.o.v.). You should now be able to build it without errors. I suggest to build it using the `build-and-run-dev` npm script. Let me know if it works as expected

**Comment by ribugent** [comment]
Hi @ericvilla 

just tested and it works, thank you very much!
